#pragma config(Sensor, in1,    lineFollow,     sensorLineFollower)
#pragma config(Sensor, in2,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  Button,         sensorTouch)
#pragma config(Sensor, dgtl3,  Quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11, Green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//Part 4)C
//Make the servo position itself to the left or right depending
//on whether the line follower is covered by your hand. This
//behavior will only apply if the button is pressed; if the button
//is released, the servo is in a middle position, awaiting the button
//to be pressed again
	while (2==2)
{
   while (SensorValue(Button)==1)
   {
      if (SensorValue(lineFollow) >2000)
      {
      	setServo(Servo, 120);
      }
      else
      {
      setServo(Servo, -120);
      }
   }
   setServo(Servo, 0);
}

}
