#pragma config(Sensor, in1,    lineFollow,     sensorLineFollower)
#pragma config(Sensor, in2,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  Button,         sensorTouch)
#pragma config(Sensor, dgtl3,  Quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11, Green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//Part 2)
	while (1==1) //repeat indefinitely
	{
	   while (SensorValue(limitSwitch)==1) //repeat while limitSwitch pressed
	   {
	      if (SensorValue(lightSensor) >1500)  //respond to lightSensor
	      {
	      	turnFlashlightOn(Flashlight, 150);
	      }
	      else
	      {
	      	turnFlashlightOff(Flashlight);
	      }
	   }
	    turnFlashlightOff(Flashlight); //do this when the limitSwitch is not pressed
	}
}
