#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  BumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, Green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void LEDControl();
task main()
{
 int motorCount; //Defines a function
  motorCount = 0; //tells where motorCount starts
  while (motorCount < 3)
  {
    startMotor(RightMotor, 95);
    wait(2);
    stopMotor(RightMotor);
    wait(2);
    motorCount = motorCount + 1; // shows how motorCount increases
  }
//runs the motor back and forth 3 times
  wait(10);

  int MotorCount;
  MotorCount = 0;
  while (MotorCount < 20)
  {
    startMotor(RightMotor, 95);
    wait(.5);
    stopMotor(RightMotor);
    wait(.5);
    MotorCount = MotorCount + 1;
  }
  //runs the motor back and fourth 20 times
  wait (10);

    int biggest;
  while (1==1)
  {
     biggest = 0;
     while (SensorValue(BumpSwitch)==0)
     {
        if (SensorValue(potentiometer)>biggest)//records smallest value on potentiometer
   {
 biggest=SensorValue(potentiometer);
        }
     }
  }

  wait (10);


  while (1==1)
     {
        LEDControl();  //function call
     }
  }
  void LEDControl()  //function definition
  {
     if (SensorValue(BumpSwitch)==1) //if bump switch is pressed the light turns on
     {
        turnLEDOn(Green);
     }
     else //if not the LED is off
     {
        turnLEDOff(Green);
     }
}
