#pragma config(Sensor, in3,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in4,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, in5,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Headlight1,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port8,           Headlight2,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port9,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task turn
{
	 startMotor(leftMotor, 100);
	 startMotor(rightMotor, -100);
}//this program makes the robot turn on its center axis

task go
{
	startMotor(leftMotor, 120);
	startMotor(rightMotor,120);
}//this task makes the robot drive forward

task waterbottleup
{
 startMotor(clawMotor, 30);
 wait(1);
 stopMotor(clawMotor);
 wait(5);
 startMotor(clawMotor,-30);
 wait(1);
 stopMotor(clawMotor);
 startMotor(armMotor, -40);
 untilPotentiometerGreaterThan(Potentiometer)>2000;
 stopMotor(armMotor);
 untilSonarLessThan (Sonar, 12);
 startMotor (clawMotor,40);
 wait(1.5);
 stopMotor(clawMotor);
}//this task picks up then later releases the waterbottle

task main()
{
	while(true)
	{
	while(vexRT(Btn8L)==1)
		{
			startTask(turn);
		}
	while(vexRT(Btn8U)==1)
		{
			startTask(go);
		}
	}
}
