#pragma config(Motor,  port1,           rightdrive,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          leftdrive,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (vexRT(Btn8D)==1)
		{
			 startMotor(clawMotor, -40);
			 wait(1);
			 stopMotor(clawMotor);
		}


}
