#pragma config(Sensor, in1,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in2,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  killSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Headlight1,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port8,           Headlight2,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port9,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task waterbottleup
{
 turnFlashlightOn(Headlight1, 100);
 turnFlashlightOn(Headlight2, 100);
 untilButtonPress(Btn8R);
 turnFlashlightOff(Headlight1);
 turnFlashlightOff(Headlight2);
 startMotor(clawMotor, 40);
 wait(1.5);
 stopMotor(clawMotor);
 forward(10);
 wait(3);
 stopMotor(leftMotor);
 stopMotor(rightMotor);
 startMotor(clawMotor,-30);
 wait(1);
 stopMotor(clawMotor);
 startMotor(armMotor, -40);
 untilPotentiometerGreaterThan(Potentiometer)>2000;
 stopMotor(armMotor);
 untilSonarLessThan (Sonar, 12);
 startMotor (clawMotor,40);
 wait(1.5);
 stopMotor(clawMotor);
}

task main()
{
 while(1==1)
 {
   if (vexRT(Btn8U)==1)
	   {
	     forward(120);
	   }
 	 if (vexRT(Btn8L)==1)
	 	 {
	 	   startMotor(rightMotor, 50);
	     wait(5);
	  	 stopMotor(rightMotor);
	   }
   if (vexRT(Btn8R)==1)
 		 {
 		   startTask (waterbottleup);
 		 }
 	 if (SensorValue(killSwitch)==1)
 	 	{
 	 		stopTask(waterbottleup);
 	 		stopMotor(armMotor);
 	 		stopMotor(clawMotor);
 	 		stopMotor(leftMotor);
 	 		stopMotor(rightMotor);
 	 	}
 	 if (SensorValue(lineSensor) <1500)
 		{
 			backward(50);
 			wait(2);
 			pointTurn(right, 100);
 			wait(1.5);
    }
	}
}
