#pragma config(Sensor, in3,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in4,    lineSensor,     sensorLineFollower)
#pragma config(Sensor, in5,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Headlight1,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port8,           Headlight2,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port9,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task leftturn
{
 swingTurn(left, 25);
 wait(2);
 stop();
}//this task is used to turn the robot left to stop the robot from running off the mat

task avoidred
{
 backward(50);
 wait(2);
 pointTurn(left,100);
 wait(1.5);
}//helps avoid the red tape, will be paired with the lightsensor

task go
{
	forward(120);
}//this task makes the robot drive forward

task rightturn
{
	 pointTurn(right,100);
}//this program makes the robot turn to the right on its center axis

task waterbottleup
{
 turnFlashlightOn(Headlight1, 100);
 turnFlashlightOn(Headlight2, 100);
 untilButtonPress(Btn8R);
 turnFlashlightOff(Headlight1);
 turnFlashlightOff(Headlight2);
 startMotor(clawMotor, 40);
 wait(1.5);
 stopMotor(clawMotor);
 forward(10);
 wait(3);
 stopMotor(leftMotor);
 stopMotor(rightMotor);
 startMotor(clawMotor,-30);
 wait(1);
 stopMotor(clawMotor);
 startMotor(armMotor, -40);
 untilPotentiometerGreaterThan(Potentiometer)>2000;
 stopMotor(armMotor);
 untilSonarLessThan (Sonar, 12);
 startMotor (clawMotor,40);
 wait(1.5);
 stopMotor(clawMotor);
}//this task picks up then later releases the waterbottle

task killSwitch
{
		stopMotor(clawMotor);
 	 	stopMotor(armMotor);
 	 	stopMotor(rightMotor);
 	 	stopMotor(leftMotor);
 	 	stopTask (go);
 	 	stopTask (leftturn);
 	 	stopTask (rightturn);
 	 	stopTask (waterbottleup);
 	 	stopTask (avoidred);
}//this task stops everything incase the robot runs off the mats or
//something goes wrong so that we dont have to jump all over the robot

task main()
{
 while(true)
 {
   if (vexRT(Btn8U)==1)
	   {
	     startTask(go);
	   }
 	 if (vexRT(Btn8L)==1)
	 	 {
	 	   startTask (rightturn);
	   }
   if (vexRT(Btn8R)==1)
 		 {
 		   startTask (waterbottleup);
 		 }
  if (SensorValue(lineSensor) <1500)
 		{
 		startTask(avoidred);
    }
  if (SensorValue(lightSensor) <350)
  	{
  		startTask(avoidred);
  	}
  while(vexRT(Btn8U)==1)
 	 	{
 	 		if (vexRT(Btn8R)==1)
 	 		 {
 	 		startTask(killSwitch);
 	 		 }
 	 	}
 	while(vexRT(Btn8U)==1)
 		{
 			if(vexRT(Btn8L)==1)
 			 {
 			   startTask(leftturn);
 			 }
 		}
	}
}
