#pragma config(Sensor, in1,    light,          sensorReflection)
#pragma config(Motor,  port1,           lefty,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

if (SensorValue(light)>100)
{
	startMotor(lefty);
}

}
