#pragma config(Sensor, in2,    linefollower,   sensorLineFollower)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
if (SensorValue(linefollower)>200)
	{
		startMotor(port1,50);
	}
}
